### ISSUE TITLE
LUA ERROR - Something to d owith "Chomp"?

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#38] opened 2022-09-04 15:57 UTC
This LUA error popped up today while running through Revendreth. Sinfall. I just summoned my ghoul (DK) as I was running  which is normally no problem, but today I got this error:

> Message: ...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:130: AddOn_Chomp: Recieved an addon message that cannot be parsed, check your addons for updates. (This message will only display once per session, but there may be more unusable addon messages.)
> Time: Sun Sep  4 16:54:43 2022
> Count: 1
> Stack: ...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:130: AddOn_Chomp: Recieved an addon message that cannot be parsed, check your addons for updates. (This message will only display once per session, but there may be more unusable addon messages.)
> [string "=[C]"]: ?
> [string "=[C]"]: in function `error'
> [string "@Interface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua"]:130: in function <...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:97>
> [string "@Interface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua"]:535: in function <...rface\AddOns\XRP\Libraries\LibMSP\Chomp\Internal.lua:533>
> 
> Locals:

**Comment by Solanya** [comment] 2022-09-04 15:58
Looks like a duplicate of #37, is it still happening with 2.0.12?

**Comment by Wyr3d** [comment] 2022-09-06 23:01
Can't say for sure. Has only happened that one time so far.

**Comment by Solanya** [comment] 2022-09-07 07:10
Gonna assume it's fixed then.

**Closed by Solanya** 2022-09-07 07:10 UTC
