### ISSUE TITLE
LUA ERROR WHEN CLICKING ON NAME IN FRIENDS LIST

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#32] opened 2020-10-16 14:19 UTC
This popped up when I clicked on a name in my friends list to send them a message:

Message: Interface\AddOns\XRP\Interface\Integration\Menus.lua:54: attempt to call global 'BNGetFriendInfoByID' (a nil value)
Time: Fri Oct 16 15:17:03 2020
Count: 1
Stack: Interface\AddOns\XRP\Interface\Integration\Menus.lua:54: attempt to call global 'BNGetFriendInfoByID' (a nil value)
[string "=[C]"]: in function `BNGetFriendInfoByID'
[string "@Interface\AddOns\XRP\Interface\Integration\Menus.lua"]:54: in function <Interface\AddOns\XRP\Interface\Integration\Menus.lua:47>
[string "=[C]"]: in function `UnitPopup_HideButtons'
[string "@Interface\FrameXML\UnitPopup.lua"]:359: in function `UnitPopup_ShowMenu'
[string "@Interface\FrameXML\FriendsFrame.lua"]:235: in function `initFunction'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:1055: in function <Interface\SharedXML\UIDropDownMenu.lua:920>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Interface\FrameXML\FriendsFrame.lua"]:222: in function `FriendsFrame_ShowBNDropdown'
[string "@Interface\FrameXML\FriendsFrame.lua"]:2073: in function <Interface\FrameXML\FriendsFrame.lua:2055>

Locals: 

Other than that, XRP seems to be working fine in 9.0.1

**Comment by Ellypse** [comment] 2020-10-16 14:21
Duplicate of #31

**Comment by Solanya** [comment] 2020-10-16 14:21
I'm aware of the issue and literally right now working on the version to fix it ^^
Duplicate of #31 so closing it.

**Closed** 2020-10-16 14:21 UTC
