### ISSUE TITLE
XRP LUA errors with Retail current version

### ISSUE THREAD

**Issue by Wyr3d** [wow-rp-addons/XRP#36] opened 2022-06-02 14:49 UTC
Message: Interface\AddOns\XRP\Interface\Integration\Menus.lua:77: hooksecurefunc(): UnitPopup_OnClick is not a function
Time: Thu Jun  2 15:45:28 2022
Count: 1
Stack: Interface\AddOns\XRP\Interface\Integration\Menus.lua:77: hooksecurefunc(): UnitPopup_OnClick is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\XRP\Interface\Integration\Menus.lua"]:77: in function <Interface\AddOns\XRP\Interface\Integration\Menus.lua:74>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\XRP\Backend\Settings\Settings.lua"]:126: in function <Interface\AddOns\XRP\Backend\Settings\Settings.lua:124>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\XRP\Backend\GameEvents.lua"]:70: in function <Interface\AddOns\XRP\Backend\GameEvents.lua:67>

Locals: <none>

**Comment by Solanya** [comment] 2022-06-02 14:50
Duplicate of #35

**Comment by Meorawr** [comment] 2022-06-02 14:50
See #35.

**Closed** 2022-06-02 14:50 UTC
